
# CONSULTAS

SELECT * FROM tabela_de_clientes;

SELECT CPF, NOME FROM tabela_de_clientes;

SELECT CPF AS CPF_CLIENTE, NOME AS CLIENTE FROM tabela_de_clientes; 

SELECT * FROM tabela_de_produtos;

#CONSUTAS COM FILTROS

SELECT * FROM tabela_de_produtos WHERE CODIGO_DO_PRODUTO ='1000889';

SELECT * FROM tabela_de_produtos WHERE SABOR = 'Uva';

SELECT * FROM tabela_de_produtos WHERE SABOR = 'Laranja';

SELECT * FROM tabela_de_produtos where EMBALAGEM = 'PET';

# CONSULTA COM VALORES 

SELECT * FROM tabela_de_produtos WHERE PRECO_DE_LISTA = 19.51;

SELECT * FROM tabela_de_produtos WHERE PRECO_DE_LISTA BETWEEN 19.50 AND 19.52;

SELECT * FROM tabela_de_produtos WHERE PRECO_DE_LISTA > 19.50 AND PRECO_DE_LISTA < 19.52;

#CONSULTA COM LIKE

SELECT * FROM tabela_de_produtos WHERE SABOR LIKE '%Maça%';

SELECT * FROM tabela_de_produtos WHERE SABOR LIKE '%Maça%' AND EMBALAGEM = 'PET';

#CONSULTA CLIENTE QUE TEM O ÚLTIMO NOME MATTOS

SELECT *FROM tabela_de_clientes WHERE NOME LIKE '%Mattos';

#CONSULTA COM DISTINCT 

SELECT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos WHERE SABOR ='LARANJA';

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM tabela_de_produtos;

SELECT DISTINCT BAIRRO FROM tabela_de_clientes WHERE CIDADE = 'RIO DE JANEIRO';

#CONSULTA COM LIMIT

SELECT * FROM tabela_de_produtos WHERE SABOR ='LARANJA' LIMIT 2;

SELECT * FROM tabela_de_produtos LIMIT 2,3;

SELECT * FROM notas_fiscais WHERE DATA_VENDA = '2017-01-01' LIMIT 10;

#ORDER BY

SELECT * FROM tabela_de_produtos;

SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA;

SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM tabela_de_produtos ORDER BY NOME_DO_PRODUTO;

SELECT * FROM tabela_de_produtos ORDER BY NOME_DO_PRODUTO DESC;

SELECT * FROM tabela_de_produtos ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO ASC;

SELECT * FROM tabela_de_produtos  WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limão';

SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;

#CONSULTA COM GROUP BY 

SELECT * FROM tabela_de_clientes;

SELECT ESTADO, LIMITE_DE_CREDITO FROM tabela_de_clientes;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabela_de_clientes GROUP BY ESTADO;

SELECT EMBALAGEM, PRECO_DE_LISTA FROM tabela_de_produtos;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRODUTO_MAIS_CARO FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS CONTADOR FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) AS TOTAL_LIMITE FROM tabela_de_clientes GROUP BY BAIRRO;

SELECT BAIRRO, ESTADO, SUM(LIMITE_DE_CREDITO) AS TOTAL_LIMITE FROM tabela_de_clientes GROUP BY BAIRRO, ESTADO;

SELECT BAIRRO, ESTADO, SUM(LIMITE_DE_CREDITO) AS TOTAL_LIMITE FROM tabela_de_clientes 
WHERE CIDADE ='RIO DE JANEIRO' GROUP BY BAIRRO, ESTADO;

SELECT BAIRRO, ESTADO, SUM(LIMITE_DE_CREDITO) AS TOTAL_LIMITE FROM tabela_de_clientes
WHERE CIDADE ='RIO DE JANEIRO' GROUP BY BAIRRO, ESTADO ORDER BY ESTADO, BAIRRO;

SELECT MAX(QUANTIDADE) AS 'MAIOR QUANTIDADE' FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035';

SELECT COUNT(*) FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;

#CONSULTA COM HAVING 

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) <= 80 AND MAX(PRECO_DE_LISTA) >= 5;

SELECT CPF, COUNT(*) FROM notas_fiscais WHERE YEAR(DATA_VENDA) = 2016  GROUP BY CPF
HAVING COUNT(*) > 2000;

#CONSULTAS COM CASE

SELECT * FROM tabela_de_clientes;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
CASE
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO'
END AS STATUS_PRECO
FROM tabela_de_produtos;

SELECT EMBALAGEM,
CASE
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO'
END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM tabela_de_produtos
WHERE SABOR ='MANGA'
GROUP BY EMBALAGEM,
CASE
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO'
END 
ORDER BY EMBALAGEM;

SELECT NOME, DATA_DE_NASCIMENTO,
CASE
	WHEN YEAR(DATA_DE_NASCIMENTO) < 1990 THEN 'CLIENTES VELHOS'
    WHEN YEAR(DATA_DE_NASCIMENTO) >= 1990 AND YEAR(DATA_DE_NASCIMENTO) <= 1995 THEN 'CLIENTES JOVENS'
    ELSE 'CLIENTE CRIANÇA'
END  AS STATUS_IDADE_CLIENTE
FROM tabela_de_clientes
GROUP BY NOME, DATA_DE_NASCIMENTO ;

SELECT SABOR,
CASE
	WHEN SABOR = 'LARANJA' THEN 'MEU PREFERIDO'
    WHEN SABOR = 'UVA' THEN'ATÉ QUE É BOM'
    ELSE 'NÃO GOSTO'
END AS STATUS_DO_REFRI
FROM tabela_de_produtos
GROUP BY SABOR ORDER BY SABOR;


    



















