
#FUNÇÕES COM STRING

SELECT LTRIM('    OLA') AS RESULTADO;

SELECT RTRIM('OLÁ   ') AS RESULTADO;

SELECT TRIM('   OLÁ  ') AS RESULTADO;

SELECT CONCAT('OLÁ', ' ', 'TUDO BEM?') AS RESULTADO;

SELECT UPPER('olá tudo bem?') AS RESULTADO;

SELECT SUBSTRING('OLÁ TUDO BEM?', 5) AS RESULTADO;

SELECT SUBSTRING('OLÁ TUDO BEM?', 5, 4) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;

SELECT NOME, CONCAT(ENDERECO_1, ' ', ENDERECO_2, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO, ' ') AS RESULTADO FROM tabela_de_clientes;

SELECT NOME_DO_PRODUTO, CONCAT(EMBALAGEM, ' ', TAMANHO, ' ', SABOR,' ') AS RESULTADO FROM tabela_de_produtos;

#FUNÇÕES COM DATA

SELECT CURDATE();

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

SELECT YEAR(CURRENT_TIMESTAMP());

SELECT DAY(CURRENT_TIMESTAMP());

SELECT MONTH(CURRENT_TIMESTAMP());

SELECT MONTHNAME(CURRENT_TIMESTAMP());

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2021-01-01') AS RESULTADO;

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2002-01-09') AS RESULTADO;

SELECT CURRENT_TIMESTAMP() AS DIA_DE_HOJE, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

SELECT DATE_VENDA FROM NOTAS_FISCAIS;

SELECT DISTINCT DATA_VENDA, DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MÊS, YEAR(DATA_VENDA) AS ANO FROM notas_fiscais;

SELECT NOME, TIMESTAMPDIFF(YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS IDADE FROM tabela_de_clientes;

#FUNÇÕES MAT

SELECT CEILING(12.3334); #MAIOR INTEIRO

SELECT FLOOR(12.456);

SELECT RAND();

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO FROM itens_notas_fiscais;







